### ISSUE TITLE
User Can modify his account

### ISSUE THREAD

**Issue by annaswaheed** [manuelcastroFau/simpleStock#5]
Grab All data from SignUp Screen:
1.  Grab FirstName from textfield
2. Grab LastName from textfield
3. Grab Email from textfield
4. Grab Phone from textfield

push the data to the backend

user can change his info and test the code for user login validation and sign up.

**Comment by Velo23** [comment]
- [ ] add code for user login
- [ ] test the code for user login validation

**Comment by annaswaheed** [comment]
@Velo23 has worked on this issue but it is still not finished he is almost there and able to push data to the backend but he has an issue where he is creating a new table instead of adding columns in the user table.
