### ISSUE TITLE
create the List of stocks UI

### ISSUE THREAD

**Issue by annaswaheed** [manuelcastroFau/simpleStock#6]
we will create the swift UI and this page will be a tableview containing the Name of stock and price of the stock and it should be similar to the wireframe we have.

**Comment by Velo23** [comment]
- [ ] In our ViewController class, instantiate a UITableView object
- [ ] Setup the tableView and add constraints
- [ ]  Conform to UITableViewDelegate and UITableViewDataSource
- [ ]  Create our own custom subclass of UITableViewCell
