### ISSUE TITLE
create the detail view of stock page UI

### ISSUE THREAD

**Issue by annaswaheed** [manuelcastroFau/simpleStock#8]
this page will come after the user selects a stock from the today's trending stock page, once the user click on the stock the user will be taken to this detail view stock page UI.

in this page we will show the graph of the stock price and the stats such as 52 week high, 52 week low, dividends  etc.

Make sure to use proper constrains on the screen so it will be responsive to all iPhones, and connect the navigation buttons to work such as back.

**Comment by Velo23** [comment]
- [ ] forecast future price direction
- [ ] charts and indicators
